//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PayablesModel", "FK_InvoiceLineItems_GLAccounts", "GLAccounts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvoiceDataModel.GLAccount), "InvoiceLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvoiceDataModel.InvoiceLineItem), true)]
[assembly: EdmRelationshipAttribute("PayablesModel", "FK_InvoiceLineItems_Invoices", "Invoices", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvoiceDataModel.Invoice), "InvoiceLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvoiceDataModel.InvoiceLineItem), true)]
[assembly: EdmRelationshipAttribute("PayablesModel", "FK_Invoices_Terms", "Terms", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvoiceDataModel.Term), "Invoices", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvoiceDataModel.Invoice), true)]

#endregion

namespace InvoiceDataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PayablesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PayablesEntities object using the connection string found in the 'PayablesEntities' section of the application configuration file.
        /// </summary>
        public PayablesEntities() : base("name=PayablesEntities", "PayablesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PayablesEntities object.
        /// </summary>
        public PayablesEntities(string connectionString) : base(connectionString, "PayablesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PayablesEntities object.
        /// </summary>
        public PayablesEntities(EntityConnection connection) : base(connection, "PayablesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GLAccount> GLAccounts
        {
            get
            {
                if ((_GLAccounts == null))
                {
                    _GLAccounts = base.CreateObjectSet<GLAccount>("GLAccounts");
                }
                return _GLAccounts;
            }
        }
        private ObjectSet<GLAccount> _GLAccounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InvoiceLineItem> InvoiceLineItems
        {
            get
            {
                if ((_InvoiceLineItems == null))
                {
                    _InvoiceLineItems = base.CreateObjectSet<InvoiceLineItem>("InvoiceLineItems");
                }
                return _InvoiceLineItems;
            }
        }
        private ObjectSet<InvoiceLineItem> _InvoiceLineItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Invoice> Invoices
        {
            get
            {
                if ((_Invoices == null))
                {
                    _Invoices = base.CreateObjectSet<Invoice>("Invoices");
                }
                return _Invoices;
            }
        }
        private ObjectSet<Invoice> _Invoices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Term> Terms
        {
            get
            {
                if ((_Terms == null))
                {
                    _Terms = base.CreateObjectSet<Term>("Terms");
                }
                return _Terms;
            }
        }
        private ObjectSet<Term> _Terms;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GLAccounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGLAccounts(GLAccount gLAccount)
        {
            base.AddObject("GLAccounts", gLAccount);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InvoiceLineItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvoiceLineItems(InvoiceLineItem invoiceLineItem)
        {
            base.AddObject("InvoiceLineItems", invoiceLineItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Invoices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvoices(Invoice invoice)
        {
            base.AddObject("Invoices", invoice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Terms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTerms(Term term)
        {
            base.AddObject("Terms", term);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Invoice> spGetInvoicesDue()
        {
            return base.ExecuteFunction<Invoice>("spGetInvoicesDue");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<Invoice> spGetInvoicesDue(MergeOption mergeOption)
        {
            return base.ExecuteFunction<Invoice>("spGetInvoicesDue", mergeOption);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PayablesModel", Name="GLAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GLAccount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GLAccount object.
        /// </summary>
        /// <param name="accountNo">Initial value of the AccountNo property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static GLAccount CreateGLAccount(global::System.Int32 accountNo, global::System.String description)
        {
            GLAccount gLAccount = new GLAccount();
            gLAccount.AccountNo = accountNo;
            gLAccount.Description = description;
            return gLAccount;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountNo
        {
            get
            {
                return _AccountNo;
            }
            set
            {
                if (_AccountNo != value)
                {
                    OnAccountNoChanging(value);
                    ReportPropertyChanging("AccountNo");
                    _AccountNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AccountNo");
                    OnAccountNoChanged();
                }
            }
        }
        private global::System.Int32 _AccountNo;
        partial void OnAccountNoChanging(global::System.Int32 value);
        partial void OnAccountNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PayablesModel", "FK_InvoiceLineItems_GLAccounts", "InvoiceLineItems")]
        public EntityCollection<InvoiceLineItem> InvoiceLineItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InvoiceLineItem>("PayablesModel.FK_InvoiceLineItems_GLAccounts", "InvoiceLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InvoiceLineItem>("PayablesModel.FK_InvoiceLineItems_GLAccounts", "InvoiceLineItems", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PayablesModel", Name="Invoice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Invoice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Invoice object.
        /// </summary>
        /// <param name="invoiceID">Initial value of the InvoiceID property.</param>
        /// <param name="vendorID">Initial value of the VendorID property.</param>
        /// <param name="invoiceNumber">Initial value of the InvoiceNumber property.</param>
        /// <param name="invoiceDate">Initial value of the InvoiceDate property.</param>
        /// <param name="invoiceTotal">Initial value of the InvoiceTotal property.</param>
        /// <param name="paymentTotal">Initial value of the PaymentTotal property.</param>
        /// <param name="creditTotal">Initial value of the CreditTotal property.</param>
        /// <param name="termsID">Initial value of the TermsID property.</param>
        /// <param name="dueDate">Initial value of the DueDate property.</param>
        public static Invoice CreateInvoice(global::System.Int32 invoiceID, global::System.Int32 vendorID, global::System.String invoiceNumber, global::System.DateTime invoiceDate, global::System.Decimal invoiceTotal, global::System.Decimal paymentTotal, global::System.Decimal creditTotal, global::System.Int32 termsID, global::System.DateTime dueDate)
        {
            Invoice invoice = new Invoice();
            invoice.InvoiceID = invoiceID;
            invoice.VendorID = vendorID;
            invoice.InvoiceNumber = invoiceNumber;
            invoice.InvoiceDate = invoiceDate;
            invoice.InvoiceTotal = invoiceTotal;
            invoice.PaymentTotal = paymentTotal;
            invoice.CreditTotal = creditTotal;
            invoice.TermsID = termsID;
            invoice.DueDate = dueDate;
            return invoice;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                if (_InvoiceID != value)
                {
                    OnInvoiceIDChanging(value);
                    ReportPropertyChanging("InvoiceID");
                    _InvoiceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InvoiceID");
                    OnInvoiceIDChanged();
                }
            }
        }
        private global::System.Int32 _InvoiceID;
        partial void OnInvoiceIDChanging(global::System.Int32 value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VendorID
        {
            get
            {
                return _VendorID;
            }
            set
            {
                OnVendorIDChanging(value);
                ReportPropertyChanging("VendorID");
                _VendorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VendorID");
                OnVendorIDChanged();
            }
        }
        private global::System.Int32 _VendorID;
        partial void OnVendorIDChanging(global::System.Int32 value);
        partial void OnVendorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InvoiceNumber
        {
            get
            {
                return _InvoiceNumber;
            }
            set
            {
                OnInvoiceNumberChanging(value);
                ReportPropertyChanging("InvoiceNumber");
                _InvoiceNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InvoiceNumber");
                OnInvoiceNumberChanged();
            }
        }
        private global::System.String _InvoiceNumber;
        partial void OnInvoiceNumberChanging(global::System.String value);
        partial void OnInvoiceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime InvoiceDate
        {
            get
            {
                return _InvoiceDate;
            }
            set
            {
                OnInvoiceDateChanging(value);
                ReportPropertyChanging("InvoiceDate");
                _InvoiceDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceDate");
                OnInvoiceDateChanged();
            }
        }
        private global::System.DateTime _InvoiceDate;
        partial void OnInvoiceDateChanging(global::System.DateTime value);
        partial void OnInvoiceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal InvoiceTotal
        {
            get
            {
                return _InvoiceTotal;
            }
            set
            {
                OnInvoiceTotalChanging(value);
                ReportPropertyChanging("InvoiceTotal");
                _InvoiceTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceTotal");
                OnInvoiceTotalChanged();
            }
        }
        private global::System.Decimal _InvoiceTotal;
        partial void OnInvoiceTotalChanging(global::System.Decimal value);
        partial void OnInvoiceTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PaymentTotal
        {
            get
            {
                return _PaymentTotal;
            }
            set
            {
                OnPaymentTotalChanging(value);
                ReportPropertyChanging("PaymentTotal");
                _PaymentTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentTotal");
                OnPaymentTotalChanged();
            }
        }
        private global::System.Decimal _PaymentTotal;
        partial void OnPaymentTotalChanging(global::System.Decimal value);
        partial void OnPaymentTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CreditTotal
        {
            get
            {
                return _CreditTotal;
            }
            set
            {
                OnCreditTotalChanging(value);
                ReportPropertyChanging("CreditTotal");
                _CreditTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreditTotal");
                OnCreditTotalChanged();
            }
        }
        private global::System.Decimal _CreditTotal;
        partial void OnCreditTotalChanging(global::System.Decimal value);
        partial void OnCreditTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TermsID
        {
            get
            {
                return _TermsID;
            }
            set
            {
                OnTermsIDChanging(value);
                ReportPropertyChanging("TermsID");
                _TermsID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TermsID");
                OnTermsIDChanged();
            }
        }
        private global::System.Int32 _TermsID;
        partial void OnTermsIDChanging(global::System.Int32 value);
        partial void OnTermsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                OnDueDateChanging(value);
                ReportPropertyChanging("DueDate");
                _DueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueDate");
                OnDueDateChanged();
            }
        }
        private global::System.DateTime _DueDate;
        partial void OnDueDateChanging(global::System.DateTime value);
        partial void OnDueDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PayablesModel", "FK_InvoiceLineItems_Invoices", "InvoiceLineItems")]
        public EntityCollection<InvoiceLineItem> InvoiceLineItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InvoiceLineItem>("PayablesModel.FK_InvoiceLineItems_Invoices", "InvoiceLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InvoiceLineItem>("PayablesModel.FK_InvoiceLineItems_Invoices", "InvoiceLineItems", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PayablesModel", "FK_Invoices_Terms", "Terms")]
        public Term Term
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Term>("PayablesModel.FK_Invoices_Terms", "Terms").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Term>("PayablesModel.FK_Invoices_Terms", "Terms").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Term> TermReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Term>("PayablesModel.FK_Invoices_Terms", "Terms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Term>("PayablesModel.FK_Invoices_Terms", "Terms", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PayablesModel", Name="InvoiceLineItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InvoiceLineItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InvoiceLineItem object.
        /// </summary>
        /// <param name="invoiceID">Initial value of the InvoiceID property.</param>
        /// <param name="invoiceSequence">Initial value of the InvoiceSequence property.</param>
        /// <param name="accountNo">Initial value of the AccountNo property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static InvoiceLineItem CreateInvoiceLineItem(global::System.Int32 invoiceID, global::System.Int16 invoiceSequence, global::System.Int32 accountNo, global::System.Decimal amount, global::System.String description)
        {
            InvoiceLineItem invoiceLineItem = new InvoiceLineItem();
            invoiceLineItem.InvoiceID = invoiceID;
            invoiceLineItem.InvoiceSequence = invoiceSequence;
            invoiceLineItem.AccountNo = accountNo;
            invoiceLineItem.Amount = amount;
            invoiceLineItem.Description = description;
            return invoiceLineItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                if (_InvoiceID != value)
                {
                    OnInvoiceIDChanging(value);
                    ReportPropertyChanging("InvoiceID");
                    _InvoiceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InvoiceID");
                    OnInvoiceIDChanged();
                }
            }
        }
        private global::System.Int32 _InvoiceID;
        partial void OnInvoiceIDChanging(global::System.Int32 value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 InvoiceSequence
        {
            get
            {
                return _InvoiceSequence;
            }
            set
            {
                if (_InvoiceSequence != value)
                {
                    OnInvoiceSequenceChanging(value);
                    ReportPropertyChanging("InvoiceSequence");
                    _InvoiceSequence = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InvoiceSequence");
                    OnInvoiceSequenceChanged();
                }
            }
        }
        private global::System.Int16 _InvoiceSequence;
        partial void OnInvoiceSequenceChanging(global::System.Int16 value);
        partial void OnInvoiceSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountNo
        {
            get
            {
                return _AccountNo;
            }
            set
            {
                OnAccountNoChanging(value);
                ReportPropertyChanging("AccountNo");
                _AccountNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountNo");
                OnAccountNoChanged();
            }
        }
        private global::System.Int32 _AccountNo;
        partial void OnAccountNoChanging(global::System.Int32 value);
        partial void OnAccountNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PayablesModel", "FK_InvoiceLineItems_GLAccounts", "GLAccounts")]
        public GLAccount GLAccount
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GLAccount>("PayablesModel.FK_InvoiceLineItems_GLAccounts", "GLAccounts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GLAccount>("PayablesModel.FK_InvoiceLineItems_GLAccounts", "GLAccounts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GLAccount> GLAccountReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GLAccount>("PayablesModel.FK_InvoiceLineItems_GLAccounts", "GLAccounts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GLAccount>("PayablesModel.FK_InvoiceLineItems_GLAccounts", "GLAccounts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PayablesModel", "FK_InvoiceLineItems_Invoices", "Invoices")]
        public Invoice Invoice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invoice>("PayablesModel.FK_InvoiceLineItems_Invoices", "Invoices").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invoice>("PayablesModel.FK_InvoiceLineItems_Invoices", "Invoices").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Invoice> InvoiceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invoice>("PayablesModel.FK_InvoiceLineItems_Invoices", "Invoices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Invoice>("PayablesModel.FK_InvoiceLineItems_Invoices", "Invoices", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PayablesModel", Name="Term")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Term : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Term object.
        /// </summary>
        /// <param name="termsID">Initial value of the TermsID property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="dueDays">Initial value of the DueDays property.</param>
        public static Term CreateTerm(global::System.Int32 termsID, global::System.String description, global::System.Int16 dueDays)
        {
            Term term = new Term();
            term.TermsID = termsID;
            term.Description = description;
            term.DueDays = dueDays;
            return term;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TermsID
        {
            get
            {
                return _TermsID;
            }
            set
            {
                if (_TermsID != value)
                {
                    OnTermsIDChanging(value);
                    ReportPropertyChanging("TermsID");
                    _TermsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TermsID");
                    OnTermsIDChanged();
                }
            }
        }
        private global::System.Int32 _TermsID;
        partial void OnTermsIDChanging(global::System.Int32 value);
        partial void OnTermsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DueDays
        {
            get
            {
                return _DueDays;
            }
            set
            {
                OnDueDaysChanging(value);
                ReportPropertyChanging("DueDays");
                _DueDays = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueDays");
                OnDueDaysChanged();
            }
        }
        private global::System.Int16 _DueDays;
        partial void OnDueDaysChanging(global::System.Int16 value);
        partial void OnDueDaysChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PayablesModel", "FK_Invoices_Terms", "Invoices")]
        public EntityCollection<Invoice> Invoices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Invoice>("PayablesModel.FK_Invoices_Terms", "Invoices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Invoice>("PayablesModel.FK_Invoices_Terms", "Invoices", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
